use fabric_ast::*;
use std::fmt::Write;

pub trait CodeEmitter {
    fn emit_program(&self, program: &Program) -> String;
}

fn array_size_str(size: &ArraySize) -> String {
    match size {
        ArraySize::Fixed(n, _) => n.to_string(),
        ArraySize::Named(i) => i.name.clone(),
    }
}

// ─── Python (Webots) Emitter ─────────────────────────────────────────────

pub struct PythonEmitter;

impl CodeEmitter for PythonEmitter {
    fn emit_program(&self, program: &Program) -> String {
        let mut out = String::new();

        writeln!(out, "# Generated by Fabric compiler").unwrap();
        writeln!(out, "# Target: Webots Python controller").unwrap();
        writeln!(out).unwrap();
        writeln!(out, "from controller import Robot").unwrap();
        writeln!(out, "import math").unwrap();
        writeln!(out).unwrap();

        let sensors: Vec<&SensorDecl> = program.declarations.iter()
            .filter_map(|d| match d { Declaration::Sensor(s) => Some(s), _ => None })
            .collect();
        let actuators: Vec<&ActuatorDecl> = program.declarations.iter()
            .filter_map(|d| match d { Declaration::Actuator(a) => Some(a), _ => None })
            .collect();
        let fallbacks: Vec<&FallbackDecl> = program.declarations.iter()
            .filter_map(|d| match d { Declaration::Fallback(f) => Some(f), _ => None })
            .collect();
        let functions: Vec<&FunctionDecl> = program.declarations.iter()
            .filter_map(|d| match d { Declaration::Function(f) => Some(f), _ => None })
            .collect();
        let loops: Vec<&LoopDecl> = program.declarations.iter()
            .filter_map(|d| match d { Declaration::Loop(l) => Some(l), _ => None })
            .collect();

        for fb in &fallbacks {
            let s = &fb.sensor_name.name;
            writeln!(out, "# Fallback state for {}", s).unwrap();
            writeln!(out, "{}_fallback_active = False", s).unwrap();
            writeln!(out, "{}_last_known = 0.0", s).unwrap();
            writeln!(out, "{}_timeout_start = 0", s).unwrap();
            writeln!(out, "{}_TIMEOUT = {:.3}", s, fb.timeout.to_ms() / 1000.0).unwrap();
            writeln!(out).unwrap();
        }

        for fb in &fallbacks {
            let s = &fb.sensor_name.name;
            writeln!(out, "def fallback_{}():", s).unwrap();
            writeln!(out, "    \"\"\"Fallback when {} is unavailable\"\"\"", s).unwrap();
            writeln!(out, "    return {}_last_known", s).unwrap();
            writeln!(out).unwrap();
        }

        for func in &functions {
            let params: Vec<String> = func.params.iter()
                .map(|p| p.name.name.clone())
                .collect();
            writeln!(out, "def {}({}):", func.name.name, params.join(", ")).unwrap();
            for stmt in &func.body {
                emit_python_stmt(&mut out, stmt, 1);
            }
            writeln!(out).unwrap();
        }

        writeln!(out, "class FabricController(Robot):").unwrap();
        writeln!(out, "    def __init__(self):").unwrap();
        writeln!(out, "        super().__init__()").unwrap();
        writeln!(out, "        self.timeStep = 32").unwrap();
        writeln!(out).unwrap();

        writeln!(out, "        # Sensor initialization").unwrap();
        for sensor in &sensors {
            writeln!(out, "        self.{} = self.getDevice('{}')",
                sensor.name.name, sensor.name.name).unwrap();
            writeln!(out, "        self.{}.enable(self.timeStep)", sensor.name.name).unwrap();
        }
        writeln!(out).unwrap();

        writeln!(out, "        # Actuator initialization").unwrap();
        for actuator in &actuators {
            match &actuator.actuator_type {
                ActuatorType::Array(_, size, _) => {
                    let sz = array_size_str(size);
                    writeln!(out, "        self.{} = [self.getDevice('{}_{{}}'.format(i)) for i in range({})]",
                        actuator.name.name, actuator.name.name, sz).unwrap();
                }
                _ => {
                    writeln!(out, "        self.{} = self.getDevice('{}')",
                        actuator.name.name, actuator.name.name).unwrap();
                }
            }
        }
        writeln!(out).unwrap();

        writeln!(out, "    def run(self):").unwrap();
        writeln!(out, "        while self.step(self.timeStep) != -1:").unwrap();

        writeln!(out, "            # Read sensors").unwrap();
        for sensor in &sensors {
            writeln!(out, "            {}_raw = self.{}.getValue()",
                sensor.name.name, sensor.name.name).unwrap();
        }
        writeln!(out).unwrap();

        for fb in &fallbacks {
            let s = &fb.sensor_name.name;
            writeln!(out, "            # Fallback check for {}", s).unwrap();
            writeln!(out, "            if {}_raw is not None:", s).unwrap();
            writeln!(out, "                {}_last_known = {}_raw", s, s).unwrap();
            writeln!(out, "                {}_timeout_start = self.getTime()", s).unwrap();
            writeln!(out, "                {}_fallback_active = False", s).unwrap();
            writeln!(out, "            elif self.getTime() - {}_timeout_start > {}_TIMEOUT:", s, s).unwrap();
            writeln!(out, "                {}_fallback_active = True", s).unwrap();
            writeln!(out).unwrap();
        }

        for fb in &fallbacks {
            let s = &fb.sensor_name.name;
            writeln!(out, "            if {}_fallback_active:", s).unwrap();
            writeln!(out, "                {} = fallback_{}()", s, s).unwrap();
            writeln!(out, "            else:").unwrap();
            writeln!(out, "                {} = {}_raw", s, s).unwrap();
        }
        writeln!(out).unwrap();

        writeln!(out, "            # Control logic").unwrap();
        for loop_decl in &loops {
            for stmt in &loop_decl.body {
                emit_python_stmt(&mut out, stmt, 3);
            }
        }

        // Emit drone swarm controller if any drone declarations
        let drones: Vec<&DroneDecl> = program.declarations.iter()
            .filter_map(|d| match d { Declaration::Drone(dr) => Some(dr), _ => None })
            .collect();

        if !drones.is_empty() {
            writeln!(out).unwrap();
            writeln!(out, "# ─── Drone Swarm Controller ───").unwrap();
            for drone in &drones {
                writeln!(out, "# Swarm: {} ({} drones, spacing: {:.1}m, formation: {:?})",
                    drone.name.name, drone.count, drone.spacing, drone.formation).unwrap();
                writeln!(out, "NUM_DRONES = {}", drone.count).unwrap();
                writeln!(out, "SPACING = {:.1}", drone.spacing).unwrap();
                writeln!(out, "TARGET_HEIGHT = 3.0").unwrap();
                writeln!(out).unwrap();

                // Supervisor spawn script
                writeln!(out, "def spawn_swarm(supervisor):").unwrap();
                writeln!(out, "    \"\"\"Spawn drone swarm in {:?} formation\"\"\"", drone.formation).unwrap();
                writeln!(out, "    import math").unwrap();
                writeln!(out, "    drones = []").unwrap();
                writeln!(out, "    grid_size = int(math.sqrt(NUM_DRONES))").unwrap();
                writeln!(out, "    for i in range(NUM_DRONES):").unwrap();
                writeln!(out, "        if i == 0:").unwrap();
                writeln!(out, "            drone = supervisor.getFromDef('drone_0') or supervisor.getSelf()").unwrap();
                writeln!(out, "            drones.append(drone)").unwrap();
                writeln!(out, "            continue").unwrap();
                writeln!(out, "        row = i // grid_size").unwrap();
                writeln!(out, "        col = i % grid_size").unwrap();
                writeln!(out, "        x = (col - grid_size // 2) * SPACING").unwrap();
                writeln!(out, "        z = (row - grid_size // 2) * SPACING").unwrap();
                writeln!(out, "        drone_string = f'Mavic2Pro {{}}'").unwrap();
                writeln!(out, "        root = supervisor.getRoot()").unwrap();
                writeln!(out, "        children = root.getField('children')").unwrap();
                writeln!(out, "        children.importMFNodeFromString(-1, drone_string)").unwrap();
                writeln!(out, "        drone = supervisor.getFromDef(f'drone_{{i}}')").unwrap();
                writeln!(out, "        drones.append(drone)").unwrap();
                writeln!(out, "    return drones").unwrap();
                writeln!(out).unwrap();

                // Individual drone controller
                writeln!(out, "def drone_controller(robot):").unwrap();
                writeln!(out, "    \"\"\"Individual drone controller with collision avoidance\"\"\"").unwrap();
                writeln!(out, "    gps = robot.getDevice('gps')").unwrap();
                writeln!(out, "    gps.enable(robot.timeStep)").unwrap();
                writeln!(out, "    motors = [robot.getDevice(f'{{n}}_propeller') for n in").unwrap();
                writeln!(out, "             ['front left', 'front right', 'rear left', 'rear right']]").unwrap();
                writeln!(out, "    HOVER_SPEED = 68.5").unwrap();
                writeln!(out, "    K_P = 0.5").unwrap();
                writeln!(out, "    K_D = 1.0").unwrap();
                writeln!(out, "    while robot.step(robot.timeStep) != -1:").unwrap();
                writeln!(out, "        pos = gps.getValues()").unwrap();
                writeln!(out, "        target = float(robot.getCustomData() or '3.0')").unwrap();
                writeln!(out, "        error = target - pos[2]").unwrap();
                writeln!(out, "        thrust = HOVER_SPEED + K_P * error").unwrap();
                writeln!(out, "        for m in motors:").unwrap();
                writeln!(out, "            m.setVelocity(thrust)").unwrap();
            }
        }

        writeln!(out).unwrap();
        writeln!(out, "# Main").unwrap();
        writeln!(out, "controller = FabricController()").unwrap();
        writeln!(out, "controller.run()").unwrap();

        out
    }
}

fn emit_python_stmt(out: &mut String, stmt: &Statement, indent: usize) {
    let pad = "    ".repeat(indent);
    match stmt {
        Statement::Read { target, sensor, .. } => {
            writeln!(out, "{}{}_raw = self.{}.getValue()", pad, target.name, sensor.name).unwrap();
        }
        Statement::Write { target, value, .. } => {
            let val_str = emit_python_expr(value);
            if target.name.contains('[') {
                let parts: Vec<&str> = target.name.split('[').collect();
                let base = parts[0];
                let idx = parts[1].trim_end_matches(']');
                writeln!(out, "{}self.{}[{}].setVelocity({})", pad, base, idx, val_str).unwrap();
            } else {
                writeln!(out, "{}self.{}.setVelocity({})", pad, target.name, val_str).unwrap();
            }
        }
        Statement::Assign { target, value, .. } => {
            let val_str = emit_python_expr(value);
            if target.name.contains('[') {
                let parts: Vec<&str> = target.name.split('[').collect();
                let base = parts[0];
                let idx = parts[1].trim_end_matches(']');
                writeln!(out, "{}self.{}[{}] = {}", pad, base, idx, val_str).unwrap();
            } else {
                writeln!(out, "{}{} = {}", pad, target.name, val_str).unwrap();
            }
        }
        Statement::Let { name, value, .. } => {
            let val_str = emit_python_expr(value);
            writeln!(out, "{}{} = {}", pad, name.name, val_str).unwrap();
        }
        Statement::Return { value, .. } => {
            if let Some(expr) = value {
                let val_str = emit_python_expr(expr);
                writeln!(out, "{}return {}", pad, val_str).unwrap();
            } else {
                writeln!(out, "{}return", pad).unwrap();
            }
        }
        Statement::IfElse { condition, then_body, else_body, .. } => {
            let cond_str = emit_python_expr(condition);
            writeln!(out, "{}if {}:", pad, cond_str).unwrap();
            if then_body.is_empty() {
                writeln!(out, "{}    pass", pad).unwrap();
            } else {
                for stmt in then_body {
                    emit_python_stmt(out, stmt, indent + 1);
                }
            }
            if let Some(else_stmts) = else_body {
                writeln!(out, "{}else:", pad).unwrap();
                if else_stmts.is_empty() {
                    writeln!(out, "{}    pass", pad).unwrap();
                } else {
                    for stmt in else_stmts {
                        emit_python_stmt(out, stmt, indent + 1);
                    }
                }
            }
        }
        Statement::Expr(expr) => {
            let val_str = emit_python_expr(&expr.expr);
            writeln!(out, "{}{}", pad, val_str).unwrap();
        }
    }
}

fn emit_python_expr(expr: &Expression) -> String {
    match expr {
        Expression::Literal(lit, _) => match lit {
            Literal::Float(v) => format!("{:.2}", v),
            Literal::Int(v) => v.to_string(),
            Literal::Bool(v) => if *v { "True".into() } else { "False".into() },
            Literal::String(v) => format!("'{}'", v),
        },
        Expression::Variable(i) => i.name.clone(),
        Expression::BinaryOp { op, left, right, .. } => {
            let l = emit_python_expr(left);
            let r = emit_python_expr(right);
            let op_str = match op {
                BinOp::Add => "+",
                BinOp::Sub => "-",
                BinOp::Mul => "*",
                BinOp::Div => "/",
                BinOp::Mod => "%",
                BinOp::Eq => "==",
                BinOp::Ne => "!=",
                BinOp::Lt => "<",
                BinOp::Gt => ">",
                BinOp::Le => "<=",
                BinOp::Ge => ">=",
                BinOp::And => "and",
                BinOp::Or => "or",
            };
            format!("({} {} {})", l, op_str, r)
        }
        Expression::UnaryOp { op, expr, .. } => {
            let e = emit_python_expr(expr);
            match op {
                UnaryOp::Neg => format!("(-{})", e),
                UnaryOp::Not => format!("(not {})", e),
            }
        }
        Expression::SensorAccess { sensor, field, .. } => {
            format!("{}.{}", sensor.name, field.name)
        }
        Expression::ArrayAccess { target, index, .. } => {
            let idx = emit_python_expr(index);
            format!("{}[{}]", target.name, idx)
        }
        Expression::FunctionCall { name, args, .. } => {
            let arg_strs: Vec<String> = args.iter().map(|a| emit_python_expr(a)).collect();
            format!("{}({})", name.name, arg_strs.join(", "))
        }
        Expression::DotAccess { target, field, .. } => {
            let t = emit_python_expr(target);
            format!("{}.{}", t, field.name)
        }
        Expression::SensorMerge { sensors, weights, .. } => {
            if weights.is_empty() {
                // Equal weights: simple average
                let exprs: Vec<String> = sensors.iter().map(|s| s.name.clone()).collect();
                format!("({} / {:.1})", exprs.join(" + "), sensors.len() as f64)
            } else {
                // Weighted average
                let mut parts = Vec::new();
                for (sensor, weight) in sensors.iter().zip(weights.iter()) {
                    let w = emit_python_expr(weight);
                    parts.push(format!("({} * {})", sensor.name, w));
                }
                format!("({})", parts.join(" + "))
            }
        }
        Expression::Match { target, arms, .. } => {
            // Build ternary chain: a if cond1 else (b if cond2 else c)
            let mut result = "None".to_string();
            for arm in arms.iter().rev() {
                let body = emit_python_expr(&arm.body);
                let cond = match arm.pattern {
                    MatchPattern::Ok => format!("{} is not None", target.name),
                    MatchPattern::Timeout => format!("timeout_{}", target.name),
                    MatchPattern::Error => format!("error_{}", target.name),
                };
                result = format!("({} if {} else {})", body, cond, result);
            }
            result
        }
        Expression::Probe { sensor, .. } => {
            format!("({}_raw is not None)", sensor.name)
        }
    }
}

// ─── C (ARM) Emitter ─────────────────────────────────────────────────────

pub struct CEmitter;

impl CodeEmitter for CEmitter {
    fn emit_program(&self, program: &Program) -> String {
        let mut out = String::new();

        writeln!(out, "/* Generated by Fabric compiler */").unwrap();
        writeln!(out, "/* Target: ARM Cortex-M / Raspberry Pi */").unwrap();
        writeln!(out).unwrap();
        writeln!(out, "#include <stdio.h>").unwrap();
        writeln!(out, "#include <math.h>").unwrap();
        writeln!(out, "#include <stdint.h>").unwrap();
        writeln!(out, "#include \"hal.h\"  /* Hardware abstraction layer */").unwrap();
        writeln!(out).unwrap();

        let sensors: Vec<&SensorDecl> = program.declarations.iter()
            .filter_map(|d| match d { Declaration::Sensor(s) => Some(s), _ => None })
            .collect();
        let actuators: Vec<&ActuatorDecl> = program.declarations.iter()
            .filter_map(|d| match d { Declaration::Actuator(a) => Some(a), _ => None })
            .collect();
        let fallbacks: Vec<&FallbackDecl> = program.declarations.iter()
            .filter_map(|d| match d { Declaration::Fallback(f) => Some(f), _ => None })
            .collect();
        let loops: Vec<&LoopDecl> = program.declarations.iter()
            .filter_map(|d| match d { Declaration::Loop(l) => Some(l), _ => None })
            .collect();

        writeln!(out, "/* Sensor handles */").unwrap();
        for sensor in &sensors {
            writeln!(out, "static sensor_t {}_handle;", sensor.name.name).unwrap();
        }
        writeln!(out).unwrap();

        writeln!(out, "/* Actuator handles */").unwrap();
        for actuator in &actuators {
            match &actuator.actuator_type {
                ActuatorType::Array(_, size, _) => {
                    let sz = array_size_str(size);
                    writeln!(out, "static motor_t {}_handles[{}];", actuator.name.name, sz).unwrap();
                }
                _ => {
                    writeln!(out, "static motor_t {}_handle;", actuator.name.name).unwrap();
                }
            }
        }
        writeln!(out).unwrap();

        for fb in &fallbacks {
            let s = &fb.sensor_name.name;
            writeln!(out, "/* Fallback state for {} */", s).unwrap();
            writeln!(out, "static float {}_last_known = 0.0f;", s).unwrap();
            writeln!(out, "static uint32_t {}_timeout_start = 0;", s).unwrap();
            writeln!(out, "static int {}_fallback_active = 0;", s).unwrap();
            writeln!(out, "#define {}_TIMEOUT_MS {:.0}", s, fb.timeout.to_ms()).unwrap();
            writeln!(out).unwrap();
        }

        for fb in &fallbacks {
            let s = &fb.sensor_name.name;
            writeln!(out, "float fallback_{}(void) {{", s).unwrap();
            writeln!(out, "    return {}_last_known;", s).unwrap();
            writeln!(out, "}}").unwrap();
            writeln!(out).unwrap();
        }

        // Emit user-defined functions
        let functions: Vec<&FunctionDecl> = program.declarations.iter()
            .filter_map(|d| match d { Declaration::Function(f) => Some(f), _ => None })
            .collect();
        for func in &functions {
            let ret_ty = match &func.return_type {
                Some(Type::Primitive(PrimitiveType::F32, _)) => "float",
                Some(Type::Primitive(PrimitiveType::Bool, _)) => "int",
                _ => "float",
            };
            let params: Vec<String> = func.params.iter().map(|p| {
                let ty = match &p.ty {
                    Type::Primitive(PrimitiveType::F32, _) => "float",
                    Type::Primitive(PrimitiveType::Bool, _) => "int",
                    _ => "float",
                };
                format!("{} {}", ty, p.name.name)
            }).collect();
            writeln!(out, "{} {}({}) {{", ret_ty, func.name.name, params.join(", ")).unwrap();
            for stmt in &func.body {
                emit_c_stmt(&mut out, stmt, 1);
            }
            writeln!(out, "}}").unwrap();
            writeln!(out).unwrap();
        }

        writeln!(out, "void init_sensors(void) {{").unwrap();
        for sensor in &sensors {
            writeln!(out, "    {}_handle = sensor_init(\"{}\", GENERIC);",
                sensor.name.name, sensor.name.name).unwrap();
        }
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();

        writeln!(out, "void init_actuators(void) {{").unwrap();
        for actuator in &actuators {
            match &actuator.actuator_type {
                ActuatorType::Array(_, size, _) => {
                    let sz = array_size_str(size);
                    writeln!(out, "    for (int i = 0; i < {}; i++) {{", sz).unwrap();
                    writeln!(out, "        {}_handles[i] = motor_init(i);", actuator.name.name).unwrap();
                    writeln!(out, "    }}").unwrap();
                }
                _ => {
                    writeln!(out, "    {}_handle = motor_init(0);", actuator.name.name).unwrap();
                }
            }
        }
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();

        let deadline_ms = loops.first().map(|l| l.deadline.to_ms()).unwrap_or(32.0);
        writeln!(out, "int main(void) {{").unwrap();
        writeln!(out, "    init_sensors();").unwrap();
        writeln!(out, "    init_actuators();").unwrap();
        writeln!(out).unwrap();
        writeln!(out, "    while (1) {{").unwrap();
        writeln!(out, "        uint32_t loop_start = hal_get_time_ms();").unwrap();
        writeln!(out).unwrap();

        writeln!(out, "        /* Read sensors */").unwrap();
        for sensor in &sensors {
            writeln!(out, "        float {}_raw = sensor_read({}_handle);",
                sensor.name.name, sensor.name.name).unwrap();
        }
        writeln!(out).unwrap();

        for fb in &fallbacks {
            let s = &fb.sensor_name.name;
            writeln!(out, "        /* Fallback check for {} */", s).unwrap();
            writeln!(out, "        if (!isnan({}_raw)) {{", s).unwrap();
            writeln!(out, "            {}_last_known = {}_raw;", s, s).unwrap();
            writeln!(out, "            {}_timeout_start = loop_start;", s).unwrap();
            writeln!(out, "            {}_fallback_active = 0;", s).unwrap();
            writeln!(out, "        }} else if ((loop_start - {}_timeout_start) > {}_TIMEOUT_MS) {{",
                s, s).unwrap();
            writeln!(out, "            {}_fallback_active = 1;", s).unwrap();
            writeln!(out, "        }}").unwrap();
            writeln!(out).unwrap();
        }

        for fb in &fallbacks {
            let s = &fb.sensor_name.name;
            writeln!(out, "        float {} = {}_fallback_active ? fallback_{}() : {}_raw;",
                s, s, s, s).unwrap();
        }
        writeln!(out).unwrap();

        writeln!(out, "        /* Control logic */").unwrap();
        for loop_decl in &loops {
            for stmt in &loop_decl.body {
                emit_c_stmt(&mut out, stmt, 2);
            }
        }
        writeln!(out).unwrap();

        writeln!(out, "        /* Enforce timing deadline */").unwrap();
        writeln!(out, "        uint32_t elapsed = hal_get_time_ms() - loop_start;").unwrap();
        writeln!(out, "        if (elapsed < (uint32_t){:.0}) {{", deadline_ms).unwrap();
        writeln!(out, "            hal_sleep_ms((uint32_t){:.0} - elapsed);", deadline_ms).unwrap();
        writeln!(out, "        }}").unwrap();

        writeln!(out, "    }}").unwrap();
        writeln!(out, "    return 0;").unwrap();
        writeln!(out, "}}").unwrap();

        out
    }
}

fn emit_c_stmt(out: &mut String, stmt: &Statement, indent: usize) {
    let pad = "    ".repeat(indent);
    match stmt {
        Statement::Read { target, sensor, .. } => {
            writeln!(out, "{}float {}_raw = sensor_read({}_handle);",
                pad, target.name, sensor.name).unwrap();
        }
        Statement::Write { target, value, .. } => {
            let val_str = emit_c_expr(value);
            if target.name.contains('[') {
                let parts: Vec<&str> = target.name.split('[').collect();
                let base = parts[0];
                let idx = parts[1].trim_end_matches(']');
                writeln!(out, "{}motor_set_position({}_handles[{}], {});",
                    pad, base, idx, val_str).unwrap();
            } else {
                writeln!(out, "{}motor_set_position({}_handle, {});",
                    pad, target.name, val_str).unwrap();
            }
        }
        Statement::Assign { target, value, .. } => {
            let val_str = emit_c_expr(value);
            if target.name.contains('[') {
                let parts: Vec<&str> = target.name.split('[').collect();
                let base = parts[0];
                let idx = parts[1].trim_end_matches(']');
                writeln!(out, "{}{}_handles[{}] = {};", pad, base, idx, val_str).unwrap();
            } else {
                writeln!(out, "{}{} = {};", pad, target.name, val_str).unwrap();
            }
        }
        Statement::Let { name, value, .. } => {
            let val_str = emit_c_expr(value);
            writeln!(out, "{}float {} = {};", pad, name.name, val_str).unwrap();
        }
        Statement::Return { value, .. } => {
            if let Some(expr) = value {
                let val_str = emit_c_expr(expr);
                writeln!(out, "{}return {};", pad, val_str).unwrap();
            } else {
                writeln!(out, "{}return;", pad).unwrap();
            }
        }
        Statement::IfElse { condition, then_body, else_body, .. } => {
            let cond_str = emit_c_expr(condition);
            writeln!(out, "{}if ({}) {{", pad, cond_str).unwrap();
            for stmt in then_body {
                emit_c_stmt(out, stmt, indent + 1);
            }
            if let Some(else_stmts) = else_body {
                writeln!(out, "{}}} else {{", pad).unwrap();
                for stmt in else_stmts {
                    emit_c_stmt(out, stmt, indent + 1);
                }
            }
            writeln!(out, "{}}}", pad).unwrap();
        }
        Statement::Expr(expr) => {
            let val_str = emit_c_expr(&expr.expr);
            writeln!(out, "{}{};", pad, val_str).unwrap();
        }
    }
}

fn emit_c_expr(expr: &Expression) -> String {
    match expr {
        Expression::Literal(lit, _) => match lit {
            Literal::Float(v) => format!("{:.2}", v),
            Literal::Int(v) => v.to_string(),
            Literal::Bool(v) => if *v { "1" } else { "0" }.to_string(),
            Literal::String(v) => format!("\"{}\"", v),
        },
        Expression::Variable(i) => i.name.clone(),
        Expression::BinaryOp { op, left, right, .. } => {
            let l = emit_c_expr(left);
            let r = emit_c_expr(right);
            let op_str = match op {
                BinOp::Add => "+",
                BinOp::Sub => "-",
                BinOp::Mul => "*",
                BinOp::Div => "/",
                BinOp::Mod => "%",
                BinOp::Eq => "==",
                BinOp::Ne => "!=",
                BinOp::Lt => "<",
                BinOp::Gt => ">",
                BinOp::Le => "<=",
                BinOp::Ge => ">=",
                BinOp::And => "&&",
                BinOp::Or => "||",
            };
            format!("({} {} {})", l, op_str, r)
        }
        Expression::UnaryOp { op, expr, .. } => {
            let e = emit_c_expr(expr);
            match op {
                UnaryOp::Neg => format!("(-{})", e),
                UnaryOp::Not => format!("(!{})", e),
            }
        }
        Expression::SensorAccess { sensor, .. } => {
            format!("{}_raw", sensor.name)
        }
        Expression::ArrayAccess { target, index, .. } => {
            let idx = emit_c_expr(index);
            format!("{}[{}]", target.name, idx)
        }
        Expression::FunctionCall { name, args, .. } => {
            let arg_strs: Vec<String> = args.iter().map(|a| emit_c_expr(a)).collect();
            format!("{}({})", name.name, arg_strs.join(", "))
        }
        Expression::DotAccess { target, field, .. } => {
            let t = emit_c_expr(target);
            format!("{}.{}", t, field.name)
        }
        Expression::SensorMerge { sensors, weights, .. } => {
            if weights.is_empty() {
                let exprs: Vec<String> = sensors.iter().map(|s| s.name.clone()).collect();
                format!("({} / {:.1})", exprs.join(" + "), sensors.len() as f64)
            } else {
                let mut parts = Vec::new();
                for (sensor, weight) in sensors.iter().zip(weights.iter()) {
                    let w = emit_c_expr(weight);
                    parts.push(format!("({} * {})", sensor.name, w));
                }
                format!("({})", parts.join(" + "))
            }
        }
        Expression::Match { target, arms, .. } => {
            // In C, emit as ternary chain
            let mut result = "0.0f".to_string();
            for arm in arms.iter().rev() {
                let body = emit_c_expr(&arm.body);
                let cond = match arm.pattern {
                    MatchPattern::Ok => format!("!isnan({})", target.name),
                    MatchPattern::Timeout => format!("timeout_{}", target.name),
                    MatchPattern::Error => format!("error_{}", target.name),
                };
                result = format!("({} ? {} : {})", cond, body, result);
            }
            result
        }
        Expression::Probe { sensor, .. } => {
            format!("(!isnan({}_raw))", sensor.name)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use fabric_core::Span;

    #[test]
    fn test_python_literal() {
        let expr = Expression::Literal(Literal::Float(3.14), Span::dummy());
        assert_eq!(emit_python_expr(&expr), "3.14");
    }

    #[test]
    fn test_python_binop() {
        let expr = Expression::BinaryOp {
            op: BinOp::Add,
            left: Box::new(Expression::Literal(Literal::Int(1), Span::dummy())),
            right: Box::new(Expression::Literal(Literal::Int(2), Span::dummy())),
            span: Span::dummy(),
        };
        assert_eq!(emit_python_expr(&expr), "(1 + 2)");
    }
}
