# Generated by Fabric compiler
# Target: Webots Python controller

from controller import Robot
import math

# Fallback state for imu
imu_fallback_active = False
imu_last_known = 0.0
imu_timeout_start = 0
imu_TIMEOUT = 0.100

# Fallback state for altitude
altitude_fallback_active = False
altitude_last_known = 0.0
altitude_timeout_start = 0
altitude_TIMEOUT = 0.200

# Fallback state for gps
gps_fallback_active = False
gps_last_known = 0.0
gps_timeout_start = 0
gps_TIMEOUT = 0.500

def fallback_imu():
    """Fallback when imu is unavailable"""
    return imu_last_known

def fallback_altitude():
    """Fallback when altitude is unavailable"""
    return altitude_last_known

def fallback_gps():
    """Fallback when gps is unavailable"""
    return gps_last_known

def dead_reckoning(imu_val):
    result = (imu_val * 0.95)
    return result

class FabricController(Robot):
    def __init__(self):
        super().__init__()
        self.timeStep = 32

        # Sensor initialization
        self.imu = self.getDevice('imu')
        self.imu.enable(self.timeStep)
        self.altitude = self.getDevice('altitude')
        self.altitude.enable(self.timeStep)
        self.gps = self.getDevice('gps')
        self.gps.enable(self.timeStep)

        # Actuator initialization
        self.motors = [self.getDevice('motors_{}'.format(i)) for i in range(4)]

    def run(self):
        while self.step(self.timeStep) != -1:
            # Read sensors
            imu_raw = self.imu.getValue()
            altitude_raw = self.altitude.getValue()
            gps_raw = self.gps.getValue()

            # Fallback check for imu
            if imu_raw is not None:
                imu_last_known = imu_raw
                imu_timeout_start = self.getTime()
                imu_fallback_active = False
            elif self.getTime() - imu_timeout_start > imu_TIMEOUT:
                imu_fallback_active = True

            # Fallback check for altitude
            if altitude_raw is not None:
                altitude_last_known = altitude_raw
                altitude_timeout_start = self.getTime()
                altitude_fallback_active = False
            elif self.getTime() - altitude_timeout_start > altitude_TIMEOUT:
                altitude_fallback_active = True

            # Fallback check for gps
            if gps_raw is not None:
                gps_last_known = gps_raw
                gps_timeout_start = self.getTime()
                gps_fallback_active = False
            elif self.getTime() - gps_timeout_start > gps_TIMEOUT:
                gps_fallback_active = True

            if imu_fallback_active:
                imu = fallback_imu()
            else:
                imu = imu_raw
            if altitude_fallback_active:
                altitude = fallback_altitude()
            else:
                altitude = altitude_raw
            if gps_fallback_active:
                gps = fallback_gps()
            else:
                gps = gps_raw

            # Control logic
            gps_ok = (gps_raw is not None)
            fused_altitude = ((imu * 0.60) + (altitude * 0.40))
            mode = (1.00 if gps is not None else (0.50 if timeout_gps else (0.00 if error_gps else None)))
            target = 10.00
            err = (target - fused_altitude)
            correction = ((err * 0.50) * mode)
            self.motors[0].setVelocity(correction)
            self.motors[1].setVelocity(correction)
            self.motors[2].setVelocity(correction)
            self.motors[3].setVelocity(correction)

# Main
controller = FabricController()
controller.run()
