/* Generated by Fabric compiler */
/* Target: ARM Cortex-M / Raspberry Pi */

#include <stdio.h>
#include <math.h>
#include <stdint.h>
#include "hal.h"  /* Hardware abstraction layer */

/* Sensor handles */
static sensor_t imu_handle;
static sensor_t altitude_handle;
static sensor_t gps_handle;

/* Actuator handles */
static motor_t motors_handles[4];

/* Fallback state for imu */
static float imu_last_known = 0.0f;
static uint32_t imu_timeout_start = 0;
static int imu_fallback_active = 0;
#define imu_TIMEOUT_MS 100

/* Fallback state for altitude */
static float altitude_last_known = 0.0f;
static uint32_t altitude_timeout_start = 0;
static int altitude_fallback_active = 0;
#define altitude_TIMEOUT_MS 200

/* Fallback state for gps */
static float gps_last_known = 0.0f;
static uint32_t gps_timeout_start = 0;
static int gps_fallback_active = 0;
#define gps_TIMEOUT_MS 500

float fallback_imu(void) {
    return imu_last_known;
}

float fallback_altitude(void) {
    return altitude_last_known;
}

float fallback_gps(void) {
    return gps_last_known;
}

float dead_reckoning(float imu_val) {
    float result = (imu_val * 0.95);
    return result;
}

void init_sensors(void) {
    imu_handle = sensor_init("imu", GENERIC);
    altitude_handle = sensor_init("altitude", GENERIC);
    gps_handle = sensor_init("gps", GENERIC);
}

void init_actuators(void) {
    for (int i = 0; i < 4; i++) {
        motors_handles[i] = motor_init(i);
    }
}

int main(void) {
    init_sensors();
    init_actuators();

    while (1) {
        uint32_t loop_start = hal_get_time_ms();

        /* Read sensors */
        float imu_raw = sensor_read(imu_handle);
        float altitude_raw = sensor_read(altitude_handle);
        float gps_raw = sensor_read(gps_handle);

        /* Fallback check for imu */
        if (!isnan(imu_raw)) {
            imu_last_known = imu_raw;
            imu_timeout_start = loop_start;
            imu_fallback_active = 0;
        } else if ((loop_start - imu_timeout_start) > imu_TIMEOUT_MS) {
            imu_fallback_active = 1;
        }

        /* Fallback check for altitude */
        if (!isnan(altitude_raw)) {
            altitude_last_known = altitude_raw;
            altitude_timeout_start = loop_start;
            altitude_fallback_active = 0;
        } else if ((loop_start - altitude_timeout_start) > altitude_TIMEOUT_MS) {
            altitude_fallback_active = 1;
        }

        /* Fallback check for gps */
        if (!isnan(gps_raw)) {
            gps_last_known = gps_raw;
            gps_timeout_start = loop_start;
            gps_fallback_active = 0;
        } else if ((loop_start - gps_timeout_start) > gps_TIMEOUT_MS) {
            gps_fallback_active = 1;
        }

        float imu = imu_fallback_active ? fallback_imu() : imu_raw;
        float altitude = altitude_fallback_active ? fallback_altitude() : altitude_raw;
        float gps = gps_fallback_active ? fallback_gps() : gps_raw;

        /* Control logic */
        float gps_ok = (!isnan(gps_raw));
        float fused_altitude = ((imu * 0.60) + (altitude * 0.40));
        float mode = (!isnan(gps) ? 1.00 : (timeout_gps ? 0.50 : (error_gps ? 0.00 : 0.0f)));
        float target = 10.00;
        float err = (target - fused_altitude);
        float correction = ((err * 0.50) * mode);
        motor_set_position(motors_handles[0], correction);
        motor_set_position(motors_handles[1], correction);
        motor_set_position(motors_handles[2], correction);
        motor_set_position(motors_handles[3], correction);

        /* Enforce timing deadline */
        uint32_t elapsed = hal_get_time_ms() - loop_start;
        if (elapsed < (uint32_t)2) {
            hal_sleep_ms((uint32_t)2 - elapsed);
        }
    }
    return 0;
}
