/* Generated by Fabric compiler */
/* Target: ARM Cortex-M / Raspberry Pi */

#include <stdio.h>
#include <math.h>
#include <stdint.h>
#include "hal.h"  /* Hardware abstraction layer */

/* Sensor handles */
static sensor_t gyro_handle;
static sensor_t accelerometer_handle;

/* Actuator handles */
static motor_t servo_handles[2];

/* Fallback state for gyro */
static float gyro_last_known = 0.0f;
static uint32_t gyro_timeout_start = 0;
static int gyro_fallback_active = 0;
#define gyro_TIMEOUT_MS 50

/* Fallback state for accelerometer */
static float accelerometer_last_known = 0.0f;
static uint32_t accelerometer_timeout_start = 0;
static int accelerometer_fallback_active = 0;
#define accelerometer_TIMEOUT_MS 100

float fallback_gyro(void) {
    return gyro_last_known;
}

float fallback_accelerometer(void) {
    return accelerometer_last_known;
}

void init_sensors(void) {
    gyro_handle = sensor_init("gyro", GENERIC);
    accelerometer_handle = sensor_init("accelerometer", GENERIC);
}

void init_actuators(void) {
    for (int i = 0; i < 2; i++) {
        servo_handles[i] = motor_init(i);
    }
}

int main(void) {
    init_sensors();
    init_actuators();

    while (1) {
        uint32_t loop_start = hal_get_time_ms();

        /* Read sensors */
        float gyro_raw = sensor_read(gyro_handle);
        float accelerometer_raw = sensor_read(accelerometer_handle);

        /* Fallback check for gyro */
        if (!isnan(gyro_raw)) {
            gyro_last_known = gyro_raw;
            gyro_timeout_start = loop_start;
            gyro_fallback_active = 0;
        } else if ((loop_start - gyro_timeout_start) > gyro_TIMEOUT_MS) {
            gyro_fallback_active = 1;
        }

        /* Fallback check for accelerometer */
        if (!isnan(accelerometer_raw)) {
            accelerometer_last_known = accelerometer_raw;
            accelerometer_timeout_start = loop_start;
            accelerometer_fallback_active = 0;
        } else if ((loop_start - accelerometer_timeout_start) > accelerometer_TIMEOUT_MS) {
            accelerometer_fallback_active = 1;
        }

        float gyro = gyro_fallback_active ? fallback_gyro() : gyro_raw;
        float accelerometer = accelerometer_fallback_active ? fallback_accelerometer() : accelerometer_raw;

        /* Control logic */
        float angle = ((gyro * 0.70) + (accelerometer * 0.30));
        float target = 0.00;
        float err = (target - angle);
        float kp = 2.50;
        float correction = clamp((err * kp), (-1.00), 1.00);
        motor_set_position(servo_handles[0], correction);
        motor_set_position(servo_handles[1], (-correction));

        /* Enforce timing deadline */
        uint32_t elapsed = hal_get_time_ms() - loop_start;
        if (elapsed < (uint32_t)1) {
            hal_sleep_ms((uint32_t)1 - elapsed);
        }
    }
    return 0;
}
