# Generated by Fabric compiler
# Target: Webots Python controller

from controller import Robot
import math

# Fallback state for gyro
gyro_fallback_active = False
gyro_last_known = 0.0
gyro_timeout_start = 0
gyro_TIMEOUT = 0.050

# Fallback state for accelerometer
accelerometer_fallback_active = False
accelerometer_last_known = 0.0
accelerometer_timeout_start = 0
accelerometer_TIMEOUT = 0.100

def fallback_gyro():
    """Fallback when gyro is unavailable"""
    return gyro_last_known

def fallback_accelerometer():
    """Fallback when accelerometer is unavailable"""
    return accelerometer_last_known

def clamp(val, lo, hi):
    if (val < lo):
        return lo
    if (val > hi):
        return hi
    return val

class FabricController(Robot):
    def __init__(self):
        super().__init__()
        self.timeStep = 32

        # Sensor initialization
        self.gyro = self.getDevice('gyro')
        self.gyro.enable(self.timeStep)
        self.accelerometer = self.getDevice('accelerometer')
        self.accelerometer.enable(self.timeStep)

        # Actuator initialization
        self.servo = [self.getDevice('servo_{}'.format(i)) for i in range(2)]

    def run(self):
        while self.step(self.timeStep) != -1:
            # Read sensors
            gyro_raw = self.gyro.getValue()
            accelerometer_raw = self.accelerometer.getValue()

            # Fallback check for gyro
            if gyro_raw is not None:
                gyro_last_known = gyro_raw
                gyro_timeout_start = self.getTime()
                gyro_fallback_active = False
            elif self.getTime() - gyro_timeout_start > gyro_TIMEOUT:
                gyro_fallback_active = True

            # Fallback check for accelerometer
            if accelerometer_raw is not None:
                accelerometer_last_known = accelerometer_raw
                accelerometer_timeout_start = self.getTime()
                accelerometer_fallback_active = False
            elif self.getTime() - accelerometer_timeout_start > accelerometer_TIMEOUT:
                accelerometer_fallback_active = True

            if gyro_fallback_active:
                gyro = fallback_gyro()
            else:
                gyro = gyro_raw
            if accelerometer_fallback_active:
                accelerometer = fallback_accelerometer()
            else:
                accelerometer = accelerometer_raw

            # Control logic
            angle = ((gyro * 0.70) + (accelerometer * 0.30))
            target = 0.00
            err = (target - angle)
            kp = 2.50
            correction = clamp((err * kp), (-1.00), 1.00)
            self.servo[0].setPosition(correction)
            self.servo[1].setPosition((-correction))

# Main
controller = FabricController()
controller.run()
